[package]
name = "iced_glow"
version = "0.2.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A glow renderer for iced"
license = "MIT AND OFL-1.1"
repository = "https://github.com/hecrj/iced"

[features]
canvas = ["iced_graphics/canvas"]
qr_code = ["iced_graphics/qr_code"]
default_system_font = ["iced_graphics/font-source"]
# Not supported yet!
image = []
svg = []

[dependencies]
glyph_brush = "0.7"
euclid = "0.22"
bytemuck = "1.4"
log = "0.4"
sysinfo = "0.20.5"
serde_json = "1.0"

[dependencies.glow]
version = "0.11"
git = "https://github.com/derezzedex/glow"
rev = "82842b79af83d3e3e975aa7c5b78bd3c6438e712"

[dependencies.glow_glyph]
version = "0.4"
git = "https://github.com/derezzedex/glow_glyph"
rev = "ddb7b7d6d376aced00716b9545800ececd2d40e2"

[dependencies.iced_native]
version = "0.4"
path = "../native"

[dependencies.iced_graphics]
version = "0.2"
path = "../graphics"
features = ["font-fallback", "font-icons", "opengl"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
